/* Chapter 5: reverse recap, registered strips, full-stone reveal and tracked finale.
   All narrative timing uses HMANEClock, including menu/background pauses. */
window.Chapter5 = (() => {
  'use strict';
  const K=window.HMANEClock, base='./assets/chapter5/', CANCEL=Symbol('chapter5-cancel');
  const root=document.createElement('main'); root.id='c5'; root.hidden=true;
  root.innerHTML=`<canvas id="c5-canvas" aria-label="Three scripts of the Rosetta Stone"></canvas>
    <div id="c5-captions" aria-live="polite"></div>
    <section id="c5-copy" aria-live="polite"><h1></h1><p></p></section>
    <section id="c5-topic" aria-live="polite"></section>
    <p id="c5-status" role="status"></p>
    <button id="c5-next" hidden>NEXT</button><button id="c5-skip" hidden>Continue without camera</button>`;
  document.body.append(root);
  const E=id=>document.getElementById('c5-'+id),ctx=E('canvas').getContext('2d'),images=new Map(),pending=new Map();
  const mix=(a,b,t)=>a+(b-a)*t, ease=t=>t*t*(3-2*t), out=t=>1-(1-t)*(1-t), clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
  let active=false,busy=false,beat=0,epoch=0,data,loading,frameID,arSession=0,arSystem=null,arLive=false,found=false,foundAt=0,lostAt=0,arTickID;
  let S={}, cards=[], lastCheckpoint=1;
  const labels=['hieroglyphs','Demotic','Greek'];
  const colors={stela:'#000066',scripts:'#101010',ptolemy:'#ebb563'};
  const checkpoints=[1,7,9,10,13,14,16,17];
  function delay(ms){const e=epoch;return new Promise((res,rej)=>{const id=K.timeout(()=>{pending.delete(id);e===epoch?res():rej(CANCEL);},ms);pending.set(id,rej);});}
  async function tween(ms,fn){const e=epoch,start=K.now();do{if(e!==epoch)throw CANCEL;const t=clamp((K.now()-start)/Math.max(ms,1));fn(t);draw();if(t===1)return;await delay(16);}while(true);}
  function cancel(){epoch++;for(const [id,rej] of pending){K.clear(id);rej(CANCEL);}pending.clear();}
  function run(fn){Promise.resolve().then(fn).catch(err=>{if(err===CANCEL)return;console.error('Chapter 5',err);busy=false;E('status').textContent='This step could not load. Please retry.';button('RETRY',()=>start(lastCheckpoint));});}
  function loadImage(src){if(images.has(src))return Promise.resolve(images.get(src));return new Promise((res,rej)=>{const im=new Image();im.onload=()=>{images.set(src,im);res(im);};im.onerror=()=>rej(Error('Unable to load '+src));im.src=src;});}
  async function ready(){if(!loading)loading=(async()=>{const response=await fetch(base+'mapping.json');if(!response.ok)throw Error('Chapter 5 mapping unavailable');data=await response.json();await Promise.all(['rosetta-phone.jpg',...data.strips.flatMap(d=>['name-'+d.id+'.jpg','strip-'+d.id+'.jpg'])].map(p=>loadImage(base+p)).concat(['stela-zoomed.jpg','stela-zoomed-overlay.jpg'].map(p=>loadImage('./assets/images/'+p))));})().catch(e=>{loading=null;throw e;});await loading;}
  function layout(){const W=root.clientWidth,H=root.clientHeight,w=Math.min(W*.90,H*.56),h=w*374/1048;return {W,H,w,h,x:(W-w)/2,ys:[Math.max(64,H*.05),H*.465-h/2,H*.81-h/2]};}
  function photoRect(){const {W,H}=layout(),im=images.get(base+'rosetta-phone.jpg');if(!im)return {x:0,y:0,w:0,h:0};const s=Math.min(W*.96/im.width,H*.80/im.height);return{x:(W-im.width*s)/2,y:H*.025,w:im.width*s,h:im.height*s};}
  function cardRect(i){const L=layout();return{x:L.x,y:cards[i]?.y==null?L.ys[i]:cards[i].y*L.H,w:L.w,h:L.h};}
  function setBeat(n){beat=n;root.dataset.beat=n;busy=true;E('next').hidden=true;E('skip').hidden=true;E('status').textContent='';clearCopy();clearCaptions();HMANENav.setBack(null);draw();}
  function button(label,fn){busy=false;const b=E('next');b.textContent=label;b.hidden=false;b.disabled=false;b.onclick=()=>{b.hidden=true;b.onclick=null;run(fn);};HMANENav.setBack(()=>start(checkpoints.filter(n=>n<lastCheckpoint).pop()||1));}
  function clearCopy(){S.overlay=false;S.focus=null;E('copy').hidden=true;}
  function clearCaptions(){S.captions=[];E('captions').replaceChildren();}
  function captions(text){S.captions=text;E('captions').replaceChildren(...text.map(t=>{const p=document.createElement('p');p.textContent=t;return p;}));placeText();}
  function placeText(){const L=layout();[...E('captions').children].forEach((p,i)=>{const r=cardRect(i);Object.assign(p.style,{left:r.x+'px',top:r.y+r.h+8+'px',width:r.w+'px'});});const r=cardRect(0);Object.assign(E('copy').style,{left:r.x+'px',top:r.y+r.h+L.H*.05+'px',width:r.w+'px',maxHeight:Math.max(80,L.H-(r.y+r.h+L.H*.05)-90)+'px'});}
  function copy(title,body){S.overlay=true;E('copy').hidden=false;E('copy').querySelector('h1').textContent=title;E('copy').querySelector('p').textContent=body;placeText();draw();}
  async function overlay(n,title,body,next,focus=null){setBeat(n);lastCheckpoint=n;S.focus=focus;copy(title,body);await delay(1000);button('NEXT',next);}
  function box(d,key){return d.targets[key];}
  function initCards(key='name'){cards=data.strips.map((d,i)=>{const b=box(d,key);return {visible:true,y:null,cx:(b[0]+b[2])/2,cy:(b[1]+b[3])/2,scale:1,target:key,mode:'strip',alpha:1};});}
  function naturalScale(i){const L=layout(),b=box(data.strips[i],'name');return (L.w*.86)/(b[2]-b[0]);}
  function fitScale(i,key){const L=layout(),b=box(data.strips[i],key),s=naturalScale(i);return Math.min(1,L.w*.88/((b[2]-b[0])*s),L.h*.87/((b[3]-b[1])*s));}
  function setTarget(key){initCards(key);cards.forEach((c,i)=>c.scale=fitScale(i,key));}
  function drawCard(i){const c=cards[i];if(!c?.visible)return;const d=data.strips[i],r=cardRect(i);ctx.save();ctx.globalAlpha=c.alpha??1;ctx.fillStyle='#fff';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.beginPath();ctx.rect(r.x,r.y,r.w,r.h);ctx.clip();
    if(c.mode==='name'){const im=images.get(base+'name-'+d.id+'.jpg'),s=Math.min(r.w/im.width,r.h/im.height);ctx.drawImage(im,r.x+(r.w-im.width*s)/2,r.y+(r.h-im.height*s)/2,im.width*s,im.height*s);}
    else {const im=images.get(base+'strip-'+d.id+'.jpg'),s=naturalScale(i)*c.scale,period=d.width+32;const k=Math.round(c.cx/period);for(let j=k-1;j<=k+1;j++){const x=r.x+r.w/2+(j*period-c.cx)*s,y=r.y+r.h/2-c.cy*s;ctx.drawImage(im,x,y,d.width*s,d.height*s);ctx.fillStyle='#111';ctx.fillRect(x+(d.width+16)*s,r.y+8,1,r.h-16);}}
    if(c.cross!=null){const im=images.get(base+'name-'+d.id+'.jpg'),s=Math.min(r.w/im.width,r.h/im.height);ctx.globalAlpha*=1-c.cross;ctx.drawImage(im,r.x+(r.w-im.width*s)/2,r.y+(r.h-im.height*s)/2,im.width*s,im.height*s);}
    ctx.restore();ctx.save();ctx.globalAlpha=c.alpha??1;ctx.lineWidth=3;ctx.strokeStyle='#ebb563';ctx.strokeRect(r.x+1.5,r.y+1.5,r.w-3,r.h-3);ctx.restore();
    if(i===0&&S.focus)drawFocus(r);
  }
  function stelaPlateRect(){const r=cardRect(0),d=data.strips[0],b=d.targets.stela,s=naturalScale(0)*cards[0].scale;return{x:r.x+r.w/2-(b[2]-b[0])*s/2,y:r.y+r.h/2-(b[3]-b[1])*s/2,w:(b[2]-b[0])*s,h:(b[3]-b[1])*s};}
  function drawFocus(r){if(S.focus==='writing'){const d=data.strips[0],b=d.targets[cards[0].target],s=naturalScale(0)*cards[0].scale;const x0=cards[0].target==='demotic'?2903:3270,x1=cards[0].target==='demotic'?3000:3381;ctx.save();ctx.strokeStyle='#ebb563';ctx.lineWidth=3;ctx.strokeRect(r.x+r.w/2+(x0-cards[0].cx)*s,r.y+r.h/2+(b[1]-cards[0].cy)*s,(x1-x0)*s,(b[3]-b[1])*s);ctx.restore();return;}
    const p=stelaPlateRect(),im=images.get('./assets/images/'+(S.stelaFill?'stela-zoomed-overlay.jpg':'stela-zoomed.jpg'));ctx.save();ctx.filter='brightness(1.18)';ctx.drawImage(im,85,45,805,428,p.x,p.y,p.w,p.h);ctx.restore();
    const b=S.focus==='det'?[105,45,375,473]:[358,45,881,473];ctx.strokeStyle='#ebb563';ctx.lineWidth=3;ctx.strokeRect(p.x+(b[0]-85)/805*p.w,p.y,p.w*(b[2]-b[0])/805,p.h);
  }
  function transformH(p,H){const z=H[2][0]*p[0]+H[2][1]*p[1]+H[2][2];return[(H[0][0]*p[0]+H[0][1]*p[1]+H[0][2])/z,(H[1][0]*p[0]+H[1][1]*p[1]+H[1][2])/z];}
  function screenPoint(p,live=arLive){if(!live){const r=photoRect();return[r.x+p[0]/data.photo.width*r.w,r.y+p[1]/data.photo.height*r.h];}const anchor=document.getElementById('stone-target').object3D,cam=document.querySelector('a-camera').getObject3D('camera');if(!cam)return[0,0];const t=transformH(p,data.photoToTarget);anchor.updateMatrixWorld(true);const v=new AFRAME.THREE.Vector3((t[0]-data.target.width/2)/data.target.width,(data.target.height/2-t[1])/data.target.width,0);v.applyMatrix4(anchor.matrixWorld).project(cam);return[(v.x*.5+.5)*root.clientWidth,(-v.y*.5+.5)*root.clientHeight];}
  function path(points,live=arLive){const ps=points.map(p=>screenPoint(p,live));ctx.beginPath();ps.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();return ps;}
  function highlight(points,color,alpha=.28){path(points);ctx.fillStyle=`rgba(255,255,255,${alpha})`;ctx.fill();ctx.lineWidth=4;ctx.strokeStyle='rgba(255,255,255,.9)';ctx.stroke();ctx.lineWidth=2;ctx.strokeStyle=color;ctx.stroke();}
  function drawStone(){if(!arLive){const r=photoRect();ctx.fillStyle='#000066';ctx.fillRect(0,0,root.clientWidth,root.clientHeight);ctx.drawImage(images.get(base+'rosetta-phone.jpg'),r.x,r.y,r.w,r.h);}ctx.save();ctx.globalAlpha=S.highlightAlpha??1;for(const key of S.groups||[])for(const p of data.regions[key])highlight(p,colors[key],S.pulse===key?.3+.35*Math.sin((S.pulseT||0)*Math.PI)**2:.25);ctx.restore();
    if(S.scriptIndex!=null&&S.scriptIndex>=0){path(data.scriptAreas[S.scriptIndex]);ctx.fillStyle=`rgba(235,181,99,${S.scriptGlow||.15})`;ctx.fill();}
    if(S.guide){path(data.outline,false);ctx.setLineDash([7,5]);ctx.lineWidth=2;ctx.strokeStyle='#ebb563';ctx.stroke();ctx.setLineDash([]);}
  }
  function draw(){if(!active||!data||!images.has(base+'rosetta-phone.jpg'))return;root.dataset.view=S.mode;const L=layout(),dpr=Math.min(devicePixelRatio||1,2),can=E('canvas');if(can.width!==Math.round(L.W*dpr)||can.height!==Math.round(L.H*dpr)){can.width=Math.round(L.W*dpr);can.height=Math.round(L.H*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,L.W,L.H);
    if(S.mode==='stone'||S.mode==='ar'){drawStone();}
    else if(S.mode==='zoom'){drawStone();ctx.fillStyle=`rgba(0,0,102,${1-clamp(S.zoom*2)})`;ctx.fillRect(0,0,L.W,L.H);drawFlying(S.zoom);}
    else {ctx.fillStyle='#000066';ctx.fillRect(0,0,L.W,L.H);for(let i=0;i<3;i++){ctx.save();if(S.overlay&&i!==0)ctx.filter='blur(7px)';drawCard(i);ctx.restore();}if(S.overlay){const r=cardRect(0);ctx.fillStyle='rgba(0,0,0,.82)';ctx.fillRect(0,0,L.W,r.y);ctx.fillRect(0,r.y+r.h,L.W,L.H-r.y-r.h);ctx.fillRect(0,r.y,r.x,r.h);ctx.fillRect(r.x+r.w,r.y,L.W-r.x-r.w,r.h);}}
    placeText();
  }
  function drawFlying(t){data.strips.forEach((d,i)=>{const b=d.targets.stela,src=cardRect(i),to=data.regions.stela[i].map(p=>screenPoint(p,false));const dest={x:Math.min(...to.map(p=>p[0])),y:Math.min(...to.map(p=>p[1])),w:Math.max(...to.map(p=>p[0]))-Math.min(...to.map(p=>p[0])),h:Math.max(...to.map(p=>p[1]))-Math.min(...to.map(p=>p[1]))};const q=ease(t),r={};for(const k of ['x','y','w','h'])r[k]=mix(src[k],dest[k],q);const s=naturalScale(i)*cards[i].scale,sourceW=src.w/s,sourceH=src.h/s,cx=(b[0]+b[2])/2,cy=(b[1]+b[3])/2;const sx=mix(cx-sourceW/2,b[0],q),sy=mix(cy-sourceH/2,b[1],q),sw=mix(sourceW,b[2]-b[0],q),sh=mix(sourceH,b[3]-b[1],q);ctx.save();ctx.globalAlpha=1-clamp((t-.75)/.25);ctx.fillStyle='#fff';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.beginPath();ctx.rect(r.x,r.y,r.w,r.h);ctx.clip();const im=images.get(base+'strip-'+d.id+'.jpg');ctx.drawImage(im,r.x-sx/sw*r.w,r.y-sy/sh*r.h,d.width/sw*r.w,d.height/sh*r.h);ctx.restore();ctx.save();ctx.globalAlpha=1-t;ctx.strokeStyle='#ebb563';ctx.lineWidth=3;ctx.strokeRect(r.x,r.y,r.w,r.h);ctx.restore();});}
  async function pan(key,ms){clearCopy();clearCaptions();const old=cards.map(c=>({...c}));const specs=data.strips.map((d,i)=>{const b=d.targets[key],period=d.width+32;let dest=(b[0]+b[2])/2;while(d.direction>0&&dest<old[i].cx)dest+=period;while(d.direction<0&&dest>old[i].cx)dest-=period;return{dest,cy:(b[1]+b[3])/2,scale:fitScale(i,key)};});
    // Reset previous fit over .5s, then pan and reserve .5s for a new fit.
    // Short .5s pans perform all three concurrently, preserving their duration.
    await tween(ms,t=>{const elapsed=t*ms;cards.forEach((c,i)=>{const o=old[i],d=specs[i],reset=o.scale<.999?500:0,fit=d.scale<.999?500:0,short=ms<=reset+fit;const p=short?t:clamp((elapsed-reset)/(ms-reset-fit));c.cx=mix(o.cx,d.dest,ease(p));c.cy=mix(o.cy,d.cy,ease(p));c.scale=short?mix(o.scale,d.scale,ease(t)):elapsed<reset?mix(o.scale,1,ease(elapsed/reset)):elapsed>ms-fit?mix(1,d.scale,ease((elapsed-(ms-fit))/fit)):1;});});cards.forEach((c,i)=>{const b=data.strips[i].targets[key];c.cx=(b[0]+b[2])/2;c.cy=(b[1]+b[3])/2;c.scale=specs[i].scale;c.target=key;});draw();}
  async function collide(i,duration){const L=layout(),incoming=cards[i],upper=cards[i-1],final= L.ys[i]/L.H,upperFinal=L.ys[i-1]/L.H,contact=upperFinal+L.h/L.H;incoming.visible=true;incoming.y=1.05;await tween(duration,t=>incoming.y=mix(1.05,contact,ease(t)));
    const displacement=i===1?upperFinal+L.h/L.H*.33:Math.min(L.ys[0]/L.H+L.h/L.H*.33,.20,Math.max(.01,upperFinal-(L.ys[0]/L.H+L.h/L.H-.025))),peak=upperFinal-displacement,downStart=contact-.006;
    await tween(750,t=>{const ms=t*750;upper.y=ms<200?mix(upperFinal,peak,out(ms/200)):ms<250?peak:mix(peak,upperFinal,out((ms-250)/500));incoming.y=ms<100?mix(contact,downStart,out(ms/100)):ms<150?downStart:mix(downStart,final,out((ms-150)/600));if(i===2){const top=cards[0],penetration=Math.max(0,L.ys[0]/L.H+L.h/L.H-upper.y);top.y=L.ys[0]/L.H-Math.min(.025,penetration);}});cards.forEach(c=>c.y=null);draw();}
  async function opening(){setBeat(1);initCards();cards.forEach((c,i)=>{c.mode='name';c.visible=i===0;});await delay(500);setBeat(2);await collide(1,1250);await delay(500);setBeat(3);await collide(2,700);captions(labels.map(l=>'Ptolemy’s name in '+l+'.'));await delay(2000);setBeat(4);cards.forEach(c=>{c.mode='strip';c.cross=0;});await tween(300,t=>cards.forEach(c=>c.cross=t));cards.forEach(c=>delete c.cross);setBeat(5);E('status').textContent='Rewinding the decree across three scripts.';await pan('greek',3000);await delay(1000);setBeat(6);captions(labels.map(l=>'“Greek script” in '+l+'.'));await delay(2500);await greek();}
  async function greek(){await overlay(7,'LETTERS, NOT WRITING','The decree requires its text to be written in three scripts. Here, the hieroglyphic text calls Greek “letters.” Greek is alphabetic: this choice of words distinguishes it from the “writing” used to describe the Egyptian scripts.',async()=>{setBeat(8);await pan('demotic',500);await delay(500);captions(labels.map(l=>'“Demotic writing” in '+l+'.'));await delay(2500);await demotic();});}
  async function demotic(){await overlay(9,'NATIVE WRITING','The hieroglyphic text calls Demotic “native writing.” Notice the writing sign: unlike the term “letters” for Greek, it names Demotic as writing.',async()=>{setBeat(10);await pan('hieroglyphic',500);await delay(500);captions(labels.map(l=>'“Hieroglyphic writing” in '+l+'.'));await delay(2000);await sacred();},'writing');}
  async function sacred(){await overlay(10,'SACRED WRITING','The hieroglyphic text calls this “sacred writing.” Remember the writing sign? It looks like an Egyptian scribal kit—the tools you explored in Chapter 3.',async()=>{setBeat(11);await pan('stela',2000);await delay(1000);setBeat(12);captions(['“Stela” in hieroglyphs.','“Stela” in Demotic.','Greek word for stela—missing here.']);await delay(2500);await determinative();},'writing');}
  async function determinative(){setBeat(13);lastCheckpoint=13;copy('STELA','A stela is an upright stone slab bearing an inscription or image. These signs name the stone itself.');await delay(1000);S.focus='det';copy('DETERMINATIVE','A stela is an upright stone slab bearing an inscription or image. This determinative explains the word’s meaning without adding a sound. Its outline is the shape of a stela.');await delay(1000);button('NEXT',async()=>{S.stelaFill=true;draw();await delay(500);await phonograms();});}
  async function phonograms(){S.stelaFill=false;await overlay(14,'PHONOGRAMS','These signs represent sounds. Together, they spell the Egyptian word for stela. The determinative beside them tells us what kind of thing the word names.',zoomOut,'phon');}
  async function zoomOut(){setBeat(15);S.mode='zoom';S.groups=[];S.zoom=0;await tween(2500,t=>S.zoom=t);S.mode='stone';S.groups=['stela'];draw();await delay(1000);topic('stela');await delay(2000);await overview();}
  function topic(key){S.topic=key;E('topic').hidden=false;const names={stela:'Stela',scripts:'Three scripts',ptolemy:'Ptolemy’s name'};E('topic').replaceChildren();const h=document.createElement('h2');h.textContent=names[key];E('topic').append(h);const row=document.createElement('div');row.className='c5-topic-labels';labels.forEach((l,i)=>{const p=document.createElement('p');p.textContent=key==='stela'&&i===2?'Greek word for stela—missing here.':names[key]+' in '+l+'.';row.append(p);});E('topic').append(row);}
  async function overview(){setBeat(16);lastCheckpoint=16;S.mode='stone';S.groups=['stela','scripts','ptolemy'];draw();for(const key of ['stela','scripts','ptolemy']){E('topic').hidden=true;S.pulse=key;await delay(1000);topic(key);await tween(2000,t=>S.pulseT=t);}S.pulse=null;button('NEXT',acquire);}
  function stopCamera(){arSession++;K.clear(arTickID);arTickID=null;arLive=false;found=false;root.classList.remove('c5-live');document.getElementById('ar-wrap').style.display='none';document.getElementById('ar-wrap').style.zIndex='';try{arSystem?.stop();}catch{}document.querySelectorAll('.mindar-ui-overlay').forEach(e=>e.style.display='none');}
  async function acquire(){setBeat(17);lastCheckpoint=17;S.mode='stone';S.groups=[];S.guide=true;E('topic').hidden=true;E('status').textContent='Point your camera at the stone. Match its outline loosely.';E('skip').hidden=false;E('skip').onclick=()=>fallback('Continuing on the image.');draw();const token=++arSession,start=K.now();found=false;foundAt=0;
    const scene=document.querySelector('a-scene'),target=document.getElementById('stone-target');arSystem=scene.systems?.['mindar-image-system'];if(!arSystem){fallback('Camera unavailable. Continuing on the image.');return;}
    document.getElementById('stone-model').object3D.visible=false;
    target.addEventListener('targetFound',onFound);target.addEventListener('targetLost',onLost);scene.addEventListener('arError',onError);const wrap=document.getElementById('ar-wrap');wrap.style.display='block';wrap.style.zIndex='16';
    function acquireTick(){if(!active||token!==arSession)return;const now=K.now();if(now-start>=10000){fallback('Continuing on the image.');return;}const video=scene.querySelector('video')||wrap.querySelector('video');if(video?.readyState>=2&&!arLive){arLive=true;root.classList.add('c5-live');S.mode='ar';arSystem._resize?.();}
      if(arLive&&found){const ps=data.outline.map(p=>screenPoint(p)),guide=data.outline.map(p=>screenPoint(p,false));const bounds=ps=>({x:Math.min(...ps.map(p=>p[0])),y:Math.min(...ps.map(p=>p[1])),w:Math.max(...ps.map(p=>p[0]))-Math.min(...ps.map(p=>p[0])),h:Math.max(...ps.map(p=>p[1]))-Math.min(...ps.map(p=>p[1]))});const a=bounds(ps),b=bounds(guide),ratio=a.h/b.h;const aligned=ratio>.55&&ratio<1.8&&Math.abs(a.x+a.w/2-b.x-b.w/2)<root.clientWidth*.25&&Math.abs(a.y+a.h/2-b.y-b.h/2)<root.clientHeight*.25;if(aligned){if(!foundAt)foundAt=now;if(now-foundAt>700){S.guide=false;E('skip').hidden=true;E('status').textContent='';run(finale);trackFinale(token);return;}}else{foundAt=0;E('status').textContent='Move a little closer or farther to match the outline.';}}
      draw();arTickID=K.frame(acquireTick);
    }
    arTickID=K.frame(acquireTick);
    try{await arSystem.start();if(token!==arSession){if(!active||!arLive)arSystem.stop();return;}arSystem._resize?.();document.querySelectorAll('.mindar-ui-overlay').forEach(e=>e.style.display='none');}catch(e){if(token===arSession)fallback('Camera unavailable. Continuing on the image.');}
  }
  function onFound(){if(!active||beat!==17)return;found=true;lostAt=0;}
  function onLost(){found=false;foundAt=0;if(arLive)lostAt=K.now();}
  function onError(){if(active&&beat===17)fallback('Camera unavailable. Continuing on the image.');}
  function detachAR(){document.getElementById('stone-target').removeEventListener('targetFound',onFound);document.getElementById('stone-target').removeEventListener('targetLost',onLost);document.querySelector('a-scene').removeEventListener('arError',onError);}
  function trackFinale(token){const tick=()=>{if(!active||token!==arSession)return;if(!found&&lostAt&&K.now()-lostAt>1500){fallback('Tracking lost. Continuing on the image.');return;}E('canvas').style.visibility=found?'visible':'hidden';draw();arTickID=K.frame(tick);};tick();}
  function fallback(message){if(!active||beat!==17)return;cancel();detachAR();stopCamera();E('canvas').style.visibility='';S.mode='stone';S.guide=false;E('skip').hidden=true;E('status').textContent=message;draw();run(finale);}
  async function finale(){S.highlightAlpha=1;S.guide=false;S.groups=['stela','scripts','ptolemy'];E('skip').hidden=true;for(const key of ['ptolemy','stela','scripts']){topic(key);S.pulse=key;await tween(1800,t=>S.pulseT=t);}S.pulse=null;for(let i=0;i<3;i++){S.scriptIndex=i;E('topic').innerHTML='';const h=document.createElement('h2');h.textContent=['Hieroglyphs','Demotic','Greek'][i];E('topic').append(h);await tween(1400,t=>S.scriptGlow=.30*Math.sin(Math.PI*t));}S.scriptIndex=-1;await tween(700,t=>S.highlightAlpha=1-t);S.groups=[];S.highlightAlpha=1;E('status').textContent='';E('topic').innerHTML='<h2>Three scripts. One decree.</h2><p>You can now find familiar names, words, and signs on the stone.</p>';draw();document.dispatchEvent(new CustomEvent('hmane:chapter-complete',{detail:{chapter:5}}));button('FINISH',()=>{stopCamera();detachAR();E('canvas').style.visibility='';S.mode='stone';S.groups=[];draw();E('topic').innerHTML='<h2>Thank you for exploring.</h2><p>Take another look at the stone.</p>';button('REPLAY CHAPTER',()=>start());});}
  async function launch(n){E('status').textContent='Loading chapter…';const token=epoch;await ready();if(token!==epoch||!active)throw CANCEL;E('status').textContent='';S={mode:'cards',groups:[],captions:[]};initCards();lastCheckpoint=n;draw();if(n===1)return opening();if(n===7){setTarget('greek');return greek();}if(n===9){setTarget('demotic');return demotic();}if(n===10){setTarget('hieroglyphic');return sacred();}if(n===13){setTarget('stela');return determinative();}if(n===14){setTarget('stela');return phonograms();}if(n===16){setTarget('stela');return overview();}if(n===17){setTarget('stela');S.mode='stone';return acquire();}}
  function start(n=1){stop();window.Chapter4?.stop();window.Chapter3?.stop();window.HMANELegacy?.retire();document.getElementById('gate').style.display='none';active=true;busy=true;root.hidden=false;E('topic').hidden=true;E('next').hidden=true;E('skip').hidden=true;E('copy').hidden=true;document.getElementById('contents-open').disabled=false;run(()=>launch(checkpoints.includes(n)?n:1));}
  function stop(){cancel();detachAR();stopCamera();K.clear(frameID);active=false;busy=false;root.hidden=true;E('canvas').style.visibility='';clearCaptions();}
  window.addEventListener('resize',()=>{if(active){arSystem?._resize?.();draw();}});
  window.addEventListener('pagehide',()=>{if(active)stop();});
  window.addEventListener('load',()=>{const q=new URLSearchParams(location.search);if(q.get('chapter')==='5'||q.has('ch5'))start(+q.get('ch5')||1);});
  return {start,stop,get active(){return active;},get busy(){return busy;},get beat(){return beat;},get arState(){return {live:arLive,found,stableFor:foundAt?K.now()-foundAt:0};}};
})();
